language: node_js

node_js:
    - node

os:
    - linux
    - osx

script:
    - yarn build
    - yarn setup
    - figmagic
    - \[ -d tokens \]
    - \[ -f tokens/animation.js \]

notifications:
    email: false
